---
- hosts: all
  tasks:
    - name: Get Windows version
      win_shell: "systeminfo /fo csv | select OS*, System*"
      register: windows_version

    - name: Print Windows host information
      debug:
        msg: "{{ windows_version }}"
