---
- hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Check Fortinet Firewall Version
    fortios_switch_controller_custom_command:
      vdom:  "{{ vdom }}"
      state: "present"
      access_token: "3mcNk7Qq5bnr9bqHh3g8qk4h8nycgG"
      switch_controller_custom_command:
        command: "get system status"
        command_name: "Get Fortigate OS Version"
        description: "Retrieve Fortigate OS Firmware version"
