---
- name: Check for Fortinet Firewall version
  hosts: all
  gather_facts: no
  
  tasks:
  - name : Checking Fortigate OS version
    shell: get system status
#   register: command_output

#  - debug:
#    var: command_output.stdout_lines
