---
- hosts: all
  tasks:
    - name: Get Windows version
      win_shell: "systeminfo"
      register: windows_version

    - name: Print Windows host information
      debug:
        msg: "{{ window_version }}"
