- name: Patching Window Machines
  hosts: all
  gather_facts: no
  become_method: runas

  tasks:
    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      reboot: yes